// Form dropdown options for registration

export const COUNTRIES = [
  "Philippines",
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Japan",
  "South Korea",
  "Singapore",
  "Malaysia",
  "Thailand",
  "Indonesia",
  "Vietnam",
  "India",
  "China",
  "Hong Kong",
  "Taiwan",
  "New Zealand",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "Netherlands",
  "Brazil",
  "Mexico",
  "Argentina",
  "United Arab Emirates",
  "Saudi Arabia",
  "Qatar",
].sort();

export const CIVIL_STATUS_OPTIONS = [
  "Single",
  "Married",
  "Divorced",
  "Widowed",
  "Separated",
  "In a Relationship",
  "It's Complicated",
];

export const PHILIPPINES_CITIES = [
  // Metro Manila
  "Manila",
  "Quezon City",
  "Makati",
  "Pasig",
  "Taguig",
  "Mandaluyong",
  "Pasay",
  "Parañaque",
  "Las Piñas",
  "Muntinlupa",
  "Caloocan",
  "Malabon",
  "Navotas",
  "Valenzuela",
  "Marikina",
  "San Juan",
  "Pateros",

  // Luzon
  "Baguio",
  "Angeles",
  "Olongapo",
  "Batangas City",
  "Lipa",
  "Tanauan",
  "Calapan",
  "Puerto Princesa",
  "Tagaytay",
  "Antipolo",
  "Lucena",
  "Naga",
  "Legazpi",
  "Tuguegarao",
  "Laoag",
  "Vigan",
  "San Fernando (Pampanga)",
  "San Fernando (La Union)",
  "Dagupan",
  "Urdaneta",
  "Cabanatuan",
  "San Jose",
  "Gapan",
  "Malolos",
  "Meycauayan",

  // Visayas
  "Cebu City",
  "Mandaue",
  "Lapu-Lapu",
  "Talisay (Cebu)",
  "Toledo",
  "Iloilo City",
  "Bacolod",
  "Dumaguete",
  "Tacloban",
  "Ormoc",
  "Calbayog",
  "Roxas City",
  "Tagbilaran",

  // Mindanao
  "Davao City",
  "Cagayan de Oro",
  "General Santos",
  "Zamboanga City",
  "Butuan",
  "Iligan",
  "Cotabato City",
  "Kidapawan",
  "Koronadal",
  "Malaybalay",
  "Valencia",
  "Dipolog",
  "Pagadian",
  "Ozamiz",
  "Tangub",
  "Surigao City",
  "Bislig",
  "Tandag",
  "Marawi",
].sort();

export const HOBBY_OPTIONS = [
  // Creative & Arts
  "Painting",
  "Drawing",
  "Photography",
  "Writing",
  "Poetry",
  "Playing Music",
  "Singing",
  "Dancing",
  "Acting",
  "Crafts",
  "Knitting/Crochet",
  "Digital Art",
  "Video Editing",
  "Graphic Design",

  // Sports & Fitness
  "Running",
  "Gym/Weightlifting",
  "Yoga",
  "Swimming",
  "Basketball",
  "Volleyball",
  "Badminton",
  "Tennis",
  "Football/Soccer",
  "Martial Arts",
  "Boxing",
  "Cycling",
  "Hiking",
  "Rock Climbing",
  "Skateboarding",
  "Surfing",

  // Gaming & Tech
  "Video Gaming",
  "Board Games",
  "Chess",
  "Coding/Programming",
  "Building PCs",
  "Robotics",

  // Food & Culinary
  "Cooking",
  "Baking",
  "Food Tasting",
  "Coffee Brewing",
  "Wine Tasting",

  // Outdoor & Adventure
  "Traveling",
  "Camping",
  "Fishing",
  "Gardening",
  "Bird Watching",
  "Nature Photography",

  // Entertainment & Social
  "Watching Movies",
  "Watching Series/Anime",
  "Reading Books",
  "Listening to Music",
  "Going to Concerts",
  "Karaoke",
  "Social Media",
  "Vlogging",
  "Podcasting",

  // Collection & Hobbies
  "Collecting (Coins/Stamps/etc)",
  "Fashion/Shopping",
  "Makeup/Beauty",
  "Car Enthusiast",
  "Motorcycle Riding",

  // Learning & Development
  "Learning Languages",
  "Reading Self-Help Books",
  "Meditation",
  "Volunteering",
  "Pet Care",
].sort();
